apiVersion: v1
kind: PersistentVolume
metadata:
  name: drools-storage1
  labels:
    name: drools-storage1
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  local:
    #path: /c/work/STL/MVN_REPO
    path: /Users/vksandeep/projects/jrms/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drools-storage2
  labels:
    name: drools-storage2
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  local:
    #path: /c/work/STL/MVN_REPO
    path: /Users/vksandeep/projects/jrms/vol2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
